version: '3.8'
services:
  db:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password
      POSTGRES_DB: nest_database
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
